apiVersion: extensions/v1beta1
kind : Ingress
metadata: 
  name: expo-ingress
  namespace: expo
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: expo-api-service
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /
            backend: 
              serviceName: expo-ui-service
              servicePort: 80
          - path: /api/gateway/(.+)
            backend: 
              serviceName: expo-api-service
              servicePort: 80
          - path: /api/account/(.+)
            backend: 
              serviceName: app-account-service
              servicePort: 80
          - path: /api/notification/(.+)
            backend: 
              serviceName: app-notification-service
              servicePort: 80