apiVersion: extensions/v1beta1
kind : Ingress
metadata: 
  name: ingress-gcloud
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: app-gcloud-service
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /
            backend: 
              serviceName: app-gcloud-service
              servicePort: 80
          - path: /gcloud/(.+)
            backend: 
              serviceName: app-gcloud-service
              servicePort: 80
          - path: /graphql/(.+)
            backend: 
              serviceName: app-graphql-service
              servicePort: 80