apiVersion: networking.k8s.io/v1beta1
kind : Ingress
metadata: 
  name: expo-ingress
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  # backend:
  #   serviceName: expo-api-service
  #   servicePort: 80
  rules:
    - host: bigjrcwork.com
      http:
        paths:
          - path: /
            backend: 
              serviceName: expo-ui-service
              servicePort: 80
          - path: /api/gateway/(.+)
            backend: 
              serviceName: expo-api-service
              servicePort: 80
          - path: /api/v2/([a-z0-9]+$)
            backend: 
              serviceName: expo-api-service
              servicePort: 80
