apiVersion: v1
kind: Service
metadata:
  name: {{ include "Expo.Api.name" . }}-service
  labels:
    {{- include "Expo.Api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "Expo.Api.selectorLabels" . | nindent 4 }}
